title: Young-hee Go
description: Data Scientist </br> - This page is under construction :)
site_title: 'Page-YoungheeGo'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: YoungheeGGo
blog_url: https://youngheeggo-tech.blogspot.com/
email: youngheego14@gmail.com

# absolute or relative
profile_picture: assets/images/yh-photo.jpg

# Google Analytics ID
google_analytics: 
